on:
  schedule:
    - cron:  ""
  workflow_dispatch:

name: crime-dash

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          packages: |
            any::tidyverse
            any::janitor
            any::tidyr
            any::lubridate
            any::geojsonsf
            any::sf
            any::rjson
            any::jsonlite

      - name: Execute Script
        run: |
          Rscript "dash_script.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
        
